### ISSUE TITLE
How to link it with an entity ?

### ISSUE THREAD

**Issue by cba64** [twrecked/hass-momentary#11]
Hello,

I have added a switch as per the documentation.
However, I don't understand how to link this to an entity ? 
Ultimate goal is to display a button on lovelace that would trigger this switch

Thanks for your help !

**Comment by twrecked** [comment]
Hi.

The momentary switch is just a standard switch so you can use `switch.turn_on` with the `tap_action`. I haven't had chance to test this but something like this should work:

```yaml
type: button
name: Test Momentary Switch
show_state: false
tap_action:
  action: call-service
  service: script.turn_on
  service_data:
    entity_id: switch.momentary_test
```
