### ISSUE TITLE
Can not create more than one momentary switch entity 

### ISSUE THREAD

**Issue by tecnocris** [twrecked/hass-momentary#13]
If I create a second switch entity inside the configuration.yaml, upon reboot of the core or host the system will only recognize the second entry in the config file. Is there a setting I'm missing or does the functionality to support multiple switch entities not exist?

**Comment by twrecked** [comment]
It'll support multiple entries. This is from my `configuration.yaml`:

```yaml
switch: !include switches.yaml
```

This is from my `switches.yaml`, I have about 15 in total:

```yaml
- platform: momentary
  name: "change phase to daytime"
  on_for: 1
- platform: momentary
  name: "change phase to evening"
  on_for: 1
- platform: momentary
  name: "change phase to nighttime"
  on_for: 1
```
