### ISSUE TITLE
I can't figure out how to turn off the momentary switch without having it turn on automatically.

### ISSUE THREAD

**Issue by bbigras** [twrecked/hass-momentary#20]
I'm using:

```yaml
alias: track_fan_toilette_off
description: ""
trigger:
  - platform: state
    entity_id:
      - light.fan_salle_de_bain_light
    to: "off"
condition: []
action:
  - service: homeassistant.turn_off
    data: {}
    target:
      entity_id: switch.momentary_auto_off_fan_toilette
mode: single
```

and
```yaml
switch:
- cancellable: true
  mode: 'on'
  name: auto off fan toilette
  platform: momentary
  toggle_for: 15
```

When I turn off the physical switch, `switch.momentary_auto_off_fan_toilette` turn off, but it reactivates after 15 secs.

I'm expecting my config to turn off `switch.momentary_auto_off_fan_toilette` after 15 secs but not the reverse.
