### ISSUE TITLE
Shorter "on_for" time

### ISSUE THREAD

**Issue by redskinhu** [twrecked/hass-momentary#3]
Hello

I would like to use shorter `on_for` time if it possible.
I tried smaller values than 1s but it is not working.
Is it possible change this?

Thans
Great Job

**Comment by twrecked** [comment]
I think it's possible. What sort of granularity would you need?

**Comment by redskinhu** [comment]
Hello

I need about 300ms `on_for` time. I think 100ms would be ok.

Thanks
T

**Comment by twrecked** [comment]
Still looking at this!

**Comment by redskinhu** [comment]
Great
Thanks

**Comment by twrecked** [comment]
I'm such an idiot. It all ready supports it. I use a standard `time_period` as the duration type. See the following example:

```yaml
- platform: momentary
  name: switch100
  on_for:
    milliseconds: 300
  allow_off: True
```
